on: [push]

jobs:
  deploy_job:
    
    runs-on: ubuntu-latest
    name: deploy

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: deploy file
      uses: wlixcc/SFTP-Deploy-Action@v1.2.4
      with:
        username: 'root'
        server: 'your server ip'
        ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }} 
        local_path: './foo/*'
        remote_path: '/home/mikcyons/www/kissel.ch/test'
        sftpArgs: '-o ConnectTimeout=5'

