 - name: SFTP Deploy
  uses: wlixcc/SFTP-Deploy-Action@v1.2.4
  with:
    username: 
    server: 
    port:
    ssh_private_key: 
    # will put all file under this path
    local_path: # default is ./*
    # files will copy to under remote_path
    remote_path: 
    # connection via sftp protocol only
    sftp_only: # optional
    # sftp args
    sftpArgs: # optional
    # This operation will delete all files in the remote path before upload. Please be careful set this to true
    delete_remote_files: # optional
    # SSH passsword，If a password is set, the secret key pair is ignored
    password: # optional
          
